### ISSUE TITLE
Store timezones with observations

### ISSUE THREAD

**Issue by thompchr** [chalkclassroom/CoachingApp#443]
**Is your feature request related to a problem? Please describe.**
Right now there is no record of the timezone an observation was recorded. 

**Describe the solution you'd like**
Store the timezone the observation was recorded in with the observation.

**Comment by ZachJDev** [comment]
@thompchr, What exactly did you have in mind for the use of the time zones? I've been doing a lot of research on time zones and JS Dates and Firestore timestamps, And I'm pretty sure, after this change, we'll be able to get a local time where we need it with something like, `new Date(doc.timestamp, {timezone: doc.timezone})`.

**Comment by ZachJDev** [comment]
I'm integrating my timezone changes into the branch for #444 -- the procedure it effects will be rewritten.

**Comment by ZachJDev** [comment]
Closing this issue -- changes will be in the PR for #444
