### ISSUE TITLE
Results pop-up date/time mismatch

### ISSUE THREAD

**Issue by thompchr** [chalkclassroom/CoachingApp#448]
**Describe the bug**
When you click "view results" from the post observation results pop-up the data does not contain the most recent observation. If you refresh the page, the date is correct but the teacher is missing.

**To Reproduce**
1. Create an observation
2. Finish the observation
3. Click "view results"

**Expected behavior**
Should contain today's date and the most recent observation you submitted

**Comment by ZachJDev** [comment]
Problem is that Big query insert is not finishing in time before it returns the existing data
