### ISSUE TITLE
Results pop-up layout not correct on iPad

### ISSUE THREAD

**Issue by thompchr** [chalkclassroom/CoachingApp#449]
**Describe the bug**
UI results overflow the modal area

**Comment by thompchr** [comment]
@newminoes if you get a chance, could you add a screen shot?

**Comment by newminoes** [comment]
![image](https://user-images.githubusercontent.com/56000867/144149742-f03fde24-8aa0-4d32-945c-0be470f63764.png)

**Comment by newminoes** [comment]
As you see above, the legend is cut off.

**Comment by thompchr** [comment]
I'm trying to figure out if I've fixed this. It seems like it's displaying side by side for me on two different iPads. One is the standard size and the other is the larger Pro size:
![IMG_71A7B5DB91BE-1](https://user-images.githubusercontent.com/2848483/146037723-17078a54-3acf-4032-87ad-37eaa368f7e8.jpeg)
![IMG_A5C9377139E9-1](https://user-images.githubusercontent.com/2848483/146037724-fb13c560-d9b7-4e8c-9a21-bcb06cce47a1.jpeg)
![IMG_13E20D89C32B-1](https://user-images.githubusercontent.com/2848483/146037726-f09d5a0c-180a-423e-ad0f-456f7a756116.jpeg)


Is it working for you all now @newminoes ?

**Comment by newminoes** [comment]
Yes, the legend is no longer cut off, all working now!

**Comment by thompchr** [comment]
Great! I'll mark as closed.
