### ISSUE TITLE
Action plan flow rework

### ISSUE THREAD

**Issue by thompchr** [chalkclassroom/CoachingApp#450]
There's some uncertainty around how action plans should work. Should they be on-going and open until closed? Or should there be one per day? etc.

Currently, there is an assumption of one "action plan" per area of concentration (what's the right term for this @newminoes/ @carolinehchristopher ) and it active until the coach clicks the + button the Action Plan screen off of results. The coach can view previous action plans (but not edit them) via the Action Plan. There was some uncertainty around how this should work and whether there should be multiple active action plans or whether there should only be one. There is also the question of how to best preserve history as edits are made.

@carolinehchristopher @newminoes

**Comment by newminoes** [comment]
We have requests for the action plan revisions:

**Action Plans When Viewed through Results Section**
When a coach first enters text in an action plan in the Results section, it is automatically labeled "Action Plan 1". (We will no longer need the '+' button to the right of "Action Plan")

This action plan text that was previously entered populates in the results section when viewing results from each subsequent observation until the coach sends the action plan to a "maintenance folder" by selecting a new button on the lower right of the screen. 

We would like a pop-up to appear after the user selects the maintenance folder button with this text: "Are you sure you want to send this action plan to the maintenance folder? Action plans in the maintenance folder cannot be re-opened for editing" Beneath the text we would like "Yes" and "No" buttons. 

**Mockup**:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/56000867/162525155-310308a4-46ad-4f5f-89c9-deeb7958deee.png">

Once Action Plan 1 is sent to the maintenance folder, the next time a user completes an observation and views results, the action plan form will be labeled or named "Action Plan 2" until the user sends that action plan to the maintenance folder. This process continues each time an action plan is sent to the maintenance folder. (e.g., the next Action Plan will be labeled 3). 

Each observation tool is associated with its own series of action plans. In other words, in Classroom Climate there would be Action Plan 1, Action Plan 2, etc. In Transition Time, there would be Action Plan 1 and Action Plan 2...

**Action Plans When Viewed from the Dashboard**
Replace "Achieve By" in the table with "Status." Action Plans that have been sent to the maintenance folder will be labeled "Maintenance" and action plans that are still open and appear in the Results section will be labeled "Active"

**Mockup**:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/56000867/162529170-1285afb2-0b2e-4e8e-88df-e54a6ee19093.png">

**Comment by newminoes** [comment]
We have an additional request to reformat the bottom half of the action plan form. 

**Problem**
There is a lot of extra white space between the rows in the Action Steps and Persons columns.

**Solution**
Can we decrease space/height between action step rows (row height or spacing)

Can we also change the format to 1 table instead of 3 boxes so that each row is aligned?

**Screenshot**
![Inkedchalkcoaching com_Home(iPad Air) (17)_LI](https://user-images.githubusercontent.com/56000867/164042005-be3510eb-fb84-4520-96fb-46750feecfda.jpg)

**Comment by carolinehchristopher** [comment]
@thompchr this was the other feature I was hoping we could accomplish -- adding a place where users can indicate that an action plan is in maintenance (so a button on the action plan screen that says "send to maintenance folder" and then its status shows up as maintenance instead of active)
