### ISSUE TITLE
Offline timer bug

### ISSUE THREAD

**Issue by thompchr** [chalkclassroom/CoachingApp#452]
**Description**
If the coach is offline the timers on listening to children and literacy work the first minute interval but then stops and/or goes blank. This _only_ impacts these two tools.

**Comment by newminoes** [comment]
The timer continues to freeze when offline after the first interval is complete.

**Comment by ZachJDev** [comment]
@newminoes, which tool or tools are giving you the issue? And would you be able to attach a screenshot of the app after finishing the first interval?

**Comment by newminoes** [comment]
I'm sorry! I was on my ipad testing this and forgot that I wasn't in the second environment. 
I checked in the second environment and the timers for Listening and all Literacy tools ARE working when offline. 
We can close this ticket again, thanks.

**Comment by thompchr** [comment]
﻿Katherine, can you remind me in this thread what tool it was that you were mentioning?

From: newminoes ***@***.***>
Date: Thursday, March 10, 2022 at 1:36 PM
To: chalkclassroom/CoachingApp ***@***.***>
Cc: Chris Thompson ***@***.***>, Author ***@***.***>
Subject: Re: [chalkclassroom/CoachingApp] Offline timer bug (Issue #452)

The timer continues to freeze when offline after the first interval is complete.

**Comment by newminoes** [comment]
This was in reference to the literacy tools!

From: Chris Thompson ***@***.***>
Reply-To: chalkclassroom/CoachingApp ***@***.***>
Date: Tuesday, October 11, 2022 at 3:33 AM
To: chalkclassroom/CoachingApp ***@***.***>
Cc: "Newman, Katherine M" ***@***.***>, Mention ***@***.***>
Subject: Re: [chalkclassroom/CoachingApp] Offline timer bug (Issue #452)

Katherine, can you remind me in this thread what tool it was that you were mentioning?

From: newminoes ***@***.***>
Date: Thursday, March 10, 2022 at 1:36 PM
To: chalkclassroom/CoachingApp ***@***.***>
Cc: Chris Thompson ***@***.***>, Author ***@***.***>
Subject: Re: [chalkclassroom/CoachingApp] Offline timer bug (Issue #452)

The timer continues to freeze when offline after the first interval is complete.
