### ISSUE TITLE
Lock first column for literacy results

### ISSUE THREAD

**Issue by thompchr** [chalkclassroom/CoachingApp#480]
When you scroll, you lose the left column:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/2848483/155209000-f4775863-1973-407f-9a30-8270f9e0d442.png">

Lock this so only the columns with the data scroll and the row headers remain visible.

**Comment by ZachJDev** [comment]
I believe this was addressed in #507 -- when scrolling a single table, the label column is sticky.
