### ISSUE TITLE
Calendar- creating an event

### ISSUE THREAD

**Issue by newminoes** [chalkclassroom/CoachingApp#483]
When a user creates an event in the calendar on an iPad, and selects the practice, the text is not aligned with the icon (see below).

Also, could the icons be smaller and therefore more could fit on the screen and the user would not have to scroll so much?

![Calendar](https://user-images.githubusercontent.com/56000867/155224093-18d351a8-aa5f-44af-aa39-9cf6c800f045.jpg)

**Comment by areyn77463** [comment]
@newminoes - Is this still an issue? The modal and its contents seems to scale to the screen size when I try to replicate the issue.
![image](https://user-images.githubusercontent.com/70904962/187955303-0beb3db9-3f33-4061-b95f-12d017fed676.png)
