### ISSUE TITLE
Add switcher to summary and details results pages

### ISSUE THREAD

**Issue by newminoes** [chalkclassroom/CoachingApp#515]
**Describe the solution you'd like**
Replace the two dots below the summary pie charts and details graphs with two switcher buttons that say "Teacher" and "Child" so that user are reminded that viewing both types of results is an option and it's easier to navigate between them.

**Additional context**
This change applies to the following tools: Math Instruction, Sequential Activities, and Associative and Cooperative Interactions.

**Summary example**
![image](https://user-images.githubusercontent.com/56000867/156413512-5260d173-fed9-4eab-98df-dde188de59d0.png)

**Details example**
![image](https://user-images.githubusercontent.com/56000867/156413569-39669e56-a51b-4081-a33d-9af8ff2556f6.png)

**Comment by newminoes** [comment]
Yes, thanks for catching that!

**Comment by ZachJDev** [comment]
Hopefully I'll get this and the related issues finished up today or tomorrow morning. I just wanted to check on an issue I believe I found when working on this.

In the picture below, the legend is headed 'Compare how often the **children** were:', but this does not make sense with the Teacher graphs. Can I change this to 'Compare how often the teacher:'? This typo appears on nearly all Teacher Behavior pie charts.

![TeacherPieChartLegend](https://user-images.githubusercontent.com/57590037/158242690-0c076dac-8c4a-4965-b8bf-774f54dec5be.png)

**Comment by isekmen** [comment]
Thank you so much for catching that. Yes, could you please change them all?
