### ISSUE TITLE
Methods for exporting data on saved action and conference plans

### ISSUE THREAD

**Issue by newminoes** [chalkclassroom/CoachingApp#521]
**Describe the solution you'd like**
We would like to know how many action plans and conference plans a coach has saved.
We would also like to be able to export the text they entered into the action and conference plans, if possible.

**Describe alternatives you've considered**
We also have a Calendar feature that automatically inputs the date that each coach takes the following actions: did an observation, saved an action plan, saved a conference plan (screenshot below), so there is already a function in the website that pulls this information automatically!

**Additional context**
Chris mentioned that the first step would be to figure out how the action and conference plans are stored.

![chalkcoaching com_Home(iPad Air) (15)](https://user-images.githubusercontent.com/56000867/156439122-6b03c0ba-f2f5-4823-a6de-52653137ecad.png)

**Comment by newminoes** [comment]
Here is an excel template for exporting data from saved action plans and conference plans.
[Proposed data export layout_Action and Conference plans.xlsx](https://github.com/chalkclassroom/CoachingApp/files/8327371/Proposed.data.export.layout_Action.and.Conference.plans.xlsx)

**Comment by newminoes** [comment]
Users can add any number of action steps and associated persons/timeline...but we predict that most action plans will contain 3-5 steps maximum.

**Comment by thompchr** [comment]
Got it. My only concern is that to structure the output like this, we basically have to enumerate all action plans to determine the maximum number of steps present within the set before outputting any data. Not a big deal with smaller sets, but if the number grows large could be problematic. We can try this though and see how it goes?

**Comment by ZachJDev** [comment]
Just to make sure I'm understanding the Action Plan data, there will only ever be a single goal per action plan, correct? Or can there be more than one goal?

**Comment by newminoes** [comment]
Yes, I think we do a maximum number of 5 and see how it goes?!
________________________________

**Comment by newminoes** [comment]
Yes, there is only one goal.

There can be unlimited action steps associated with the single goal, but I think we can plan to export 5 action steps and I don't think there will be many more than that in any given action plan..
________________________________

**Comment by ZachJDev** [comment]
I've implemented an export for action plans that could handle any number of steps/persons/timelines.
[Action_Plan.xlsx](https://github.com/chalkclassroom/CoachingApp/files/8334608/Action_Plan.xlsx)

For the coach / teacher IDs, do you want their names?

**Comment by ZachJDev** [comment]
Another Action Plan question -- Do you want these exportable from both the results action plan page and the main action plan page?

**Comment by newminoes** [comment]
Good question...I think it makes the most sense to export from where they are saved in the main action plan page format?
________________________________

**Comment by newminoes** [comment]
Can we have each conference plan be one row in the spreadsheet. So it would be coach ID, teacherID, date created, strengths based feedback1, strengths based feedback2, reflection question1, reflection question2, notes1, notes2, etc.? 

This layout would be similar to the action plan export.

**Comment by newminoes** [comment]
And in reference to your question about coach/teacher ID's, just their ID's would be good!

**Comment by ZachJDev** [comment]
@newminoes, reading your response made me realize that I may have been going about this incorrectly: I've been working on exporting **individual** action/conference plans, but am I correct in thinking that we actually want to be exporting **all** of a user's created action/conference plans in a single file?

Luckily, if this is the case, I don't think it will be too much more work, though I will need to go back and remove some UI elements.

**Comment by ZachJDev** [comment]
Thanks for talking me through all this! Here's a sample of a single coich's Action Plans, which I think is what we're looking for:
[Action_Plan.xlsx](https://github.com/chalkclassroom/CoachingApp/files/8373606/Action_Plan.xlsx)

Can you walk me through exporting for single/multiple users? E.g, if I'm a coach, and I go to export Action Plans, what options should be available to me? Actions created by other coaches? Or just the ability to filter based on teachers assigned to me? 
 Would it be different for Admins?

Thanks!

**Comment by thompchr** [comment]
Just a heads up that action plan export, the target demographic for that is the admin users, so this would probably go in the existing admin export area and then they would want to be able to select either a single coach or all coaches, and then export all action plans created to date. Also, can we add the associated tool to the export? This should be stored on the action plan record.
