### ISSUE TITLE
Literacy Trends  Graph styles

### ISSUE THREAD

**Issue by ZachJDev** [chalkclassroom/CoachingApp#538]
**Describe the bug**
The literacy trends table styles can be improved. see #514 for details.

**Comment by newminoes** [comment]
Hello! 

Can you move the Teacher/Child switchers to below the literacy trends table (see below)?

Also, can we change "Teacher Behaviors" and Child Behviors" to just "Teacher" and "Child" to be consistent with the language in the other tools (math example below)? Thanks!

![image001](https://user-images.githubusercontent.com/56000867/160157295-570744d9-9726-49ff-972f-c10d35d0f841.png)

![image002](https://user-images.githubusercontent.com/56000867/160157510-b4d22881-be3e-4e64-9506-d2ae79a724c3.png)
