### ISSUE TITLE
Increase space for classroom climate switcher

### ISSUE THREAD

**Issue by thompchr** [chalkclassroom/CoachingApp#544]
This is just a bit tight. Can we add some space?

<img width="520" alt="image" src="https://user-images.githubusercontent.com/2848483/159551637-d83b872d-57c4-4732-bb77-0478835807e4.png">

**Comment by thompchr** [comment]
Might actually be better to just position it fixed at the bottom of the screen as it tends to move

<img width="661" alt="image" src="https://user-images.githubusercontent.com/2848483/159551795-2d436cab-fa17-4a0c-a82d-52471db129ff.png">

<img width="574" alt="image" src="https://user-images.githubusercontent.com/2848483/159551853-123808d3-f71c-45ee-81fa-778aabdda792.png">

**Comment by ZachJDev** [comment]
I'll want to explore this a bit -- It doesn't look like it's happening on other results pages (e.g. Math Instruction), but they should be the same components...
