### ISSUE TITLE
Results preview layout issues

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#566]
The brief results preview cuts off the legend below the graph.
![ac 5](https://user-images.githubusercontent.com/65243102/170720339-031d3b37-009b-48b6-b01e-9befd10b2c42.jpg)
This is the case for associative/cooperative, classroom climate, engagement, level of instruction, listening, literacy (both foundational skills and book reading), math, and transitions.
![math 1](https://user-images.githubusercontent.com/65243102/170720790-ef1d842d-066b-4bda-9ddf-b73b9e2ae65f.jpg)

**Comment by carolinehchristopher** [comment]
![engagement results pop up](https://user-images.githubusercontent.com/65243102/173684795-99c41836-eb98-4e15-9999-018d8ad5c7d8.PNG)
This is also the case for student engagement.

**Comment by carolinehchristopher** [comment]
@MattHaslemTech Just a quick note to say if you could prioritize the results snapshot layout issue, that would be awesome.  I'm doing a bunch of app demos to try to get the word out, so this is something that would help to fix since more people are seeing it.  Thank you in advance!

**Comment by MattHaslemTech** [comment]
I believe my friend, @areyn77463, actually figured out a solution to this issue recently. It's part of the deployment that we should be rolling out for testing soon.

**Comment by carolinehchristopher** [comment]
Okay, that's great!  Thanks!
