### ISSUE TITLE
Setting up google analytics

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#572]
Today, Chris and I discussed getting google analytics set up for the site.  Here is the email and password needed to initiate that.  Will someone on your team be able to get that initiated?
We are interested in things like frequency of page visits, duration on a page, location of the person, etc.
email: chalkcoaching@gmail.com
password: chalk2020

**Comment by MattHaslemTech** [comment]
@carolinehchristopher I'm unable to access the Google Analytics dashboard with these credentials because Multi Factor Authentication is enabled on that account. Would it be possible to disable it temporarily?

**Comment by carolinehchristopher** [comment]
Check now, and hopefully I turned it off.  Sorry about that!
Otherwise, if you don't mind walking me through it, that would be helpful. Again, sorry about that!

**Comment by carolinehchristopher** [comment]
Or I could also just temporarily change the recovery email to your email address  if you'd like. (so you could just send your email to me)

**Comment by MattHaslemTech** [comment]
Oh it's no problem at all! I appreciate you doing that but unfortunately, I'm still not able to get in. 

Here are some instructions that show you how to turn off the 2-step verification: https://support.google.com/accounts/answer/1064203?hl=en&co=GENIE.Platform%3DDesktop

The verification step actually sends a verification code to your phone, so adding my e-mail might not help with this step. 

Having said that, you could also just add me to the Google Analytics team. Here are some instructions if you'd like to go that route: https://support.google.com/analytics/answer/1009702?hl=en#Add&zippy=%2Cin-this-article

**Comment by carolinehchristopher** [comment]
It's saying the two-factor is turned off already.  I'll try one of the other methods you sent
![image](https://user-images.githubusercontent.com/65243102/174862672-b49b7e27-a26e-42a9-bfa1-5f0de5cc0196.png)
![image](https://user-images.githubusercontent.com/65243102/174862698-569eb83e-6146-42e3-a658-057257d40687.png)

**Comment by carolinehchristopher** [comment]
No worries!  I never followed up either!  I will check the analytics dashboard and follow up with you.

**Comment by carolinehchristopher** [comment]
In looking at google analytics, I did have a question.  When we look at views by page title and screen class, it just lists chalk coaching with 807 views. Is it possible to get this to differentiate across the different pages within CHALK (e.g., observation of classroom climate) so we can see which pages are visited more than others?

**Comment by MattHaslemTech** [comment]
Yup! Well there is a way to see the pathname of which pages are being viewed anyway. 

You can do this by selecting Reports -> Engagement -> Pages and Screens and changing 'Page title and screen class' to 'Page path and screen class'

There might be a way for us to set it up to record custom names instead of just the pathnames. I'm not sure if it's possible but I can look into it if you'd like

![Capture3](https://user-images.githubusercontent.com/98288499/183910256-d20196be-eb0a-4707-857b-9844c3c60836.PNG)

**Comment by MattHaslemTech** [comment]
Also I just realized it might still be tracking data from us while we're viewing the site in our local environments. I'm going to get that taken care of

**Comment by carolinehchristopher** [comment]
Thanks for taking care of that!  I saw lots of activity from Norfolk -- is that where you are?  I was just curious because I don't know that we've reached out to anyone there about CHALK.

**Comment by MattHaslemTech** [comment]
No problem! But yeah that's me. I just submitted a request that should stop Analytics from tracking my data
