### ISSUE TITLE
My Teachers Calendar View

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#579]
When I go to My Teachers and switch to the calendar view (on my laptop) parts of the screen are cut off (require scrolling)

![image](https://user-images.githubusercontent.com/65243102/173844267-75d9f68f-ae94-4bed-84e6-eba2270bca4e.png)

**Comment by MattHaslemTech** [comment]
Hey @carolinehchristopher, we're not able to recreate this issue. We've tried looking at it on all various screen sizes and had no luck.

Do you know if this is still an issue? If so, would you be able to give us any insight on how we can reproduce it?

**Comment by carolinehchristopher** [comment]
Hi @MattHaslemTech I tried to recreate this issue just now as well with a coach account on the regular chalkcoaching.com, and I couldn't replicate it, so maybe we're good to go.  However, when I try to access the 2nd environment, my screen goes blank.  Should I be looking at the regular website or the 2nd environment?

**Comment by carolinehchristopher** [comment]
Scratch that!  I just cleared my cache, reloaded, and the 2nd environment worked!  Sorry about that!

**Comment by MattHaslemTech** [comment]
Okay sounds great! Thanks for letting me know
