### ISSUE TITLE
Listening to Children Results

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#582]
The prompt above the pie chart should say Engaged in listening/encouraging behaviors
![image (1)](https://user-images.githubusercontent.com/65243102/175116601-bc1d3506-96cd-4473-8bbe-e8c5fd3da58d.png)

**Comment by carolinehchristopher** [comment]
In the 2nd environment, after I do a listening observation, the results screen says I haven't completed an observation.
![image](https://user-images.githubusercontent.com/65243102/179590225-c8a684ea-864a-4131-a551-e548d60db238.png)
And when I try to select a teacher, it won't give an any teacher/option to select.
![image](https://user-images.githubusercontent.com/65243102/179590987-2d4b5f49-9146-4096-8ee3-8ad279a9173b.png)

**Comment by areyn77463** [comment]
@carolinehchristopher - I hate to bother you again but I just want to make sure that this is still an issue.

**Comment by carolinehchristopher** [comment]
@areyn77463 no worries!  I just checked it, and if I observe a teacher that hasn't previously had a listening observation, the same problem shows up (in chalkcoaching.com).  And it's also not showing results of a new observation from a teacher who has previous listening to children observations -- just pulls up old data.  so weird!

**Comment by carolinehchristopher** [comment]
Oh wait -- you're saying I should check this in the 2nd environment?

**Comment by carolinehchristopher** [comment]
@areyn77463 great news!  It worked fine when I logged into the 2nd environment.  Sorry for my confusion!

**Comment by areyn77463** [comment]
@carolinehchristopher - OK, I just wanted to make sure because I couldn't exactly replicate it other than trying to view results for a teacher that had no previous results, which seems correct. I was able to choose a different teacher with results. This may have been resolved with an earlier fix. Should we close this issue as well?

**Comment by carolinehchristopher** [comment]
As long as deploying changes made in the second environment means it will be fixed on chalkcoaching.com, I think it's fine to close it.  It did seem to work just fine in the 2nd environment, so that's good!
