### ISSUE TITLE
Storing observation results in BigQuery so we can export them

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#594]
Right now, when we export CHALK usage data, we only see things like who observed, what classroom practice they focused on, which behavior indicators they picked during the observation, and start and end time.  This is because the way CHALK is set up right now is that every time a user selects results they want to populate, the calculations are being regenerated/redone, rather than being completed initially and stored in the background.  Moving forward, could we make it so that the results calculations are done after the observation is complete and are stored, so we can export the results along with all the aforementioned information about the observation?

**Comment by thompchr** [comment]
To add a little more color, it looks like what's happening now is that BQ is storing the metadata about the observation for query purposes (submitter, date, time etc) but none of the metrics captured within the observation. When the user submits a query, the BQ query gives back the observation IDs which can then be used to fetch the detail out of Firestore. We want to store the same data in BQ as in Firestore so we can build a bulk export.

**Comment by MattHaslemTech** [comment]
Hey @carolinehchristopher, from what I understand this will involve creating new tables and adding new logic to each type of observation, so I just want to make absolutelyy sure I understand this correctly.

Currently, we have tables that store each input from an observer. But you would also like there to be another table that holds a summary of those inputs?

For example, if we were doing a 'Classroom Climate' observation, and clicked 'Disapproval' 4 times, that would create 4 rows in our current setup. But you'd also like there to be a row that just says '4' under a disapproval column?
