### ISSUE TITLE
New Pilot Users for chalkcoaching.com

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#595]
There are six people from Learning Grove in Cincinnati that are new users in CHALK.  I know the work currently being done is in the 2nd environment, but I wanted to flag that people outside of our internal team are going to be actively exploring their accounts on the regular chalkcoaching.com site in case this informs how/when changes are deployed.

**Comment by areyn77463** [comment]
@carolinehchristopher - Can you help us further understand this issue so that we can address it? Is there something you want us to add on the front-end to signify that changes have been deployed?

**Comment by carolinehchristopher** [comment]
I think this issue can be closed now, especially with all the recent fixes that have been deployed.  Thanks so much!
