### ISSUE TITLE
graph label for engagement

### ISSUE THREAD

**Issue by carolinehchristopher** [chalkclassroom/CoachingApp#649]
Not really a bug, but a change request.  I realize this doesn't have the 3 data label above the column that goes all the way up to 3 because.. it's all the way up to 3. Could we make it so that a 3 does appear above a column if that's the engagement rating?
![image](https://user-images.githubusercontent.com/65243102/207952080-6b26c846-4f87-428d-93ae-faffb99cde74.png)

**Comment by areyn77463** [comment]
Hello @carolinehchristopher, I hope all is well as we move towards the holiday. This issue and "Incorrect date on teacher results data export pdf #648" have been addressed and we would like to know if you need these pushed to staging immediately?

**Comment by carolinehchristopher** [comment]
Hi @areyn77463, I hope you're doing well, too!  I doubt any coaches are using the app this week, but it would be great to push it to staging before January 3 if it's not too much trouble.
